config/routes.rb
Rails.application.routes.draw do
  resources :memberships do
    post 'toggle_confirmed', on: :member
  end
  resources :beer_clubs
  resources :users do
    post 'toggle_blocked', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index'

  post 'places', to:'places#search'

  get 'brewerylist', to:'breweries#list'
  get 'beerlist', to:'beers#list'
  get 'kaikki_bisset', to: 'beers#index'
  
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :styles, only: [:index, :show]
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :applications, -> { where confirmed: [false, nil] }, class_name: "Membership", dependent: :destroy
  has_many :applicants, through: :applications, source: :user
  has_many :memberships, -> { where confirmed: true }, dependent: :destroy
  has_many :users, through: :memberships

  def to_s
    name
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_admin, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when 'name' then @beer_clubs.sort_by(&:name)
                  when 'founded' then @beer_clubs.sort_by(&:founded)
                  when 'city' then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    if current_user.beer_clubs.include? @beer_club
      @membership = @beer_club.memberships.detect { |membership| membership.user == current_user }
    else
      @membership = Membership.new
      @membership.beer_club_id = @beer_club.id
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        Membership.create beer_club_id: @beer_club.id, user_id: current_user.id, confirmed: true

        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club, local: true) do |form| %>
  <% if beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :founded %>
    <%= form.text_field :founded, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Beer Clubs</h1>

<p> Number of beer clubs: <%= @beer_clubs.count %> </p>

<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= link_to 'Name', beer_clubs_path(order:"name") %> </th>
      <th> <%= link_to 'Founded', beer_clubs_path(order:"founded") %> </th>
      <th> <%= link_to 'City', beer_clubs_path(order:"city") %> </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_beer_club_path(beer_club), class: "btn btn-sm btn-info" %></td>
          <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-sm btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Beer Club', new_beer_club_path) if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<h1>
  <%= @beer_club.name %>   <%= @beer_club.city %>
</h1>

<p>
  Founded: <%= @beer_club.founded %>
</p>

<div class="row">
  <div class="col-sm-4">
    <h2>
      Members
    </h2>
    <ul>
      <% @beer_club.users.each do |user| %>
        <li> <%= link_to user.username, user_path(user) %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-4">
    <h2>
      Applicants
    </h2>
    <ul>
      <% @beer_club.applications.each do |application| %>
        <li> 
          <%= link_to application.user.username, user_path(application.user) %>
          <% if current_user.beer_clubs.include? @beer_club %>
            <%= link_to "confirm", toggle_confirmed_membership_path(application.id), method: :post, class: "btn btn-danger" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<% if current_user %>
  <% if current_user.beer_clubs.include? @beer_club %>
      <%= button_to 'end the membership', @membership, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% elsif !current_user.clubs_applied_to.include? @beer_club %>
    <%= form_for(@membership) do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit class:"btn btn-primary", value:"send application to the club" %>
    <% end %>
  <% end %>
<% end %>

<%= edit_and_destroy_buttons(@beer_club) %>

<%= link_to 'Back', beer_clubs_path %>