config/routes.rb
Rails.application.routes.draw do
  resources :memberships do
    post 'toggle_confirmed', on: :member
  end
  resources :beer_clubs
  resources :users do
    post 'toggle_blocked', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index'

  post 'places', to:'places#search'

  get 'brewerylist', to:'breweries#list'
  get 'beerlist', to:'beers#list'
  get 'kaikki_bisset', to: 'beers#index'
  
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :styles, only: [:index, :show]
end

app/models/style.rb
class Style < ApplicationRecord
  include RatingAverage
  extend RatingTop

  has_many :beers
  has_many :ratings, through: :beers

  def to_s
    name
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :ensure_that_admin, only: [:destroy]

  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
    @style = Style.find(params[:id])
  end

  def destroy
  end
end

app/views/styles/index.html.erb
<h1>Listing styles</h1>

<p> Number of styles: <%= @styles.count %> </p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Style</th>
      <th>Number of beers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr> 
        <td> <%= link_to style, style_path(style) %> </td>
        <td> <%= style.beers.count %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/styles/show.html.erb
<h2> <%= @style.name %> </h2>

<p>
<%= @style.description %>
</p>

<b> beers </b>

<ul>
  <% @style.beers.each do |beer| %>
    <li> <%= link_to beer.name, beer_path(beer) %> by <%= link_to beer.brewery.name, brewery_path(beer.brewery)%> </li>
  <% end %>
</ul>

<%= link_to "Back", styles_path %> 